FROM python:3.10-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code required by the metrics exporter
COPY src ./src
COPY monitoring/. .

# Command to run the metrics exporter
CMD ["python", "metrics_exporter.py"]
