{{- if not .Values.secrets.useExternalSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    {{- include "scraping-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.postgres.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    {{- include "scraping-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.secrets.minio.rootUser | b64enc | quote }}
  root-password: {{ .Values.secrets.minio.rootPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  labels:
    {{- include "scraping-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.secrets.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.secrets.grafana.adminPassword | b64enc | quote }}
{{- end }}
