"""Unit tests for optional ML/OCR extras (#144).

Proves:
- core requirements lock does not pin torch / transformers / easyocr
- require_stage3_deps / require_stage4_deps fail fast with install hints
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from src.utils.optional_deps import (
    ML_INSTALL_HINT,
    missing_ml_packages,
    missing_ocr_packages,
    require_ml_deps,
    require_ocr_deps,
    require_stage3_deps,
    require_stage4_deps,
)

ROOT = Path(__file__).resolve().parents[2]
CORE_REQUIREMENTS = ROOT / "requirements.txt"

# Packages that must NOT appear as top-level pins in the core lock
FORBIDDEN_CORE_PINS = (
    "torch==",
    "transformers==",
    "easyocr==",
    "sentence-transformers==",
    "scikit-learn==",
    "pillow==",
    "pdf2image==",
    "pypdf2==",
)


def test_core_requirements_lock_excludes_ml_ocr_pins() -> None:
    text = CORE_REQUIREMENTS.read_text(encoding="utf-8").lower()
    assert "pip-compile" in text or "autogenerated by pip-compile" in text
    for pin in FORBIDDEN_CORE_PINS:
        assert pin not in text, f"core lock unexpectedly pins {pin}"


def test_core_requirements_documents_recompile() -> None:
    text = CORE_REQUIREMENTS.read_text(encoding="utf-8")
    assert "pip-compile" in text
    assert "requirements.in" in text


def test_require_ml_deps_fail_fast_when_missing() -> None:
    with patch("src.utils.optional_deps._missing", return_value=["torch", "transformers"]):
        with pytest.raises(ImportError) as excinfo:
            require_ml_deps("Stage 3")
    msg = str(excinfo.value)
    assert "torch" in msg
    assert "requirements-ml.txt" in msg
    assert "Install ML extras" in msg or ML_INSTALL_HINT.splitlines()[0] in msg


def test_require_ocr_deps_fail_fast_when_missing() -> None:
    with patch("src.utils.optional_deps._missing", return_value=["easyocr", "pdf2image"]):
        with pytest.raises(ImportError) as excinfo:
            require_ocr_deps("Stage 4")
    msg = str(excinfo.value)
    assert "easyocr" in msg
    assert "requirements-ocr.txt" in msg


def test_require_stage3_deps_uses_ml_check() -> None:
    with patch("src.utils.optional_deps.require_ml_deps") as mock_ml:
        require_stage3_deps()
        mock_ml.assert_called_once_with("Stage 3")


def test_require_stage4_deps_checks_ml_and_ocr() -> None:
    with patch("src.utils.optional_deps.require_ml_deps") as mock_ml, patch(
        "src.utils.optional_deps.require_ocr_deps"
    ) as mock_ocr:
        require_stage4_deps()
        mock_ml.assert_called_once_with("Stage 4")
        mock_ocr.assert_called_once_with("Stage 4")


def test_missing_helpers_return_lists() -> None:
    # Smoke: helpers return list[str] without raising
    ml = missing_ml_packages()
    ocr = missing_ocr_packages()
    assert isinstance(ml, list)
    assert isinstance(ocr, list)
