spring:
  application:
    name: warehouse-etl-loader

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uconn_warehouse}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

# ETL Configuration
etl:
  input:
    directory: ${ETL_INPUT_DIR:../data/enriched}
    file-pattern: "*.jsonl"

  batch:
    chunk-size: 100
    skip-limit: 10

  processing:
    thread-pool-size: 4

  monitoring:
    enabled: true
    metrics-interval: 1000

# Logging
logging:
  level:
    root: INFO
    edu.uconn.warehouse: DEBUG
    org.springframework.batch: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/warehouse-etl.log
    max-size: 10MB
    max-history: 30
