BOT_NAME = "uconn_ai"

SPIDER_MODULES = ["uconn_ai.spiders"]
NEWSPIDER_MODULE = "uconn_ai.spiders"

# Speed tweaks
CONCURRENT_REQUESTS = 256
CONCURRENT_REQUESTS_PER_DOMAIN = 128
CONCURRENT_REQUESTS_PER_IP = 128
DOWNLOAD_DELAY = 0
DOWNLOAD_TIMEOUT = 6
DNS_TIMEOUT = 3
RETRY_ENABLED = False
ROBOTSTXT_OBEY = False
AUTOTHROTTLE_ENABLED = False
REACTOR_THREADPOOL_MAXSIZE = 100
HTTPERROR_ALLOW_ALL = True
USER_AGENT = "UConnAI‑Crawler/0.4 (+https://uconn.edu)"
LOG_LEVEL = "INFO"

ITEM_PIPELINES = {
    "uconn_ai.pipelines.DedupAndWritePipeline": 300,
}