line-length = 120
target-version = "py311"

[lint]
select = ["E","F","I","UP","B"]
ignore = ["E501"]  # we prefer 120-char lines; ignore strict line-length rule

[lint.per-file-ignores]
"src/orchestrator/main.py" = ["E402"]  # Imports after sys.path and Windows event loop setup
