environment: development

# Scrapy settings
scrapy:
  concurrent_requests: 32
  concurrent_requests_per_domain: 16
  concurrent_requests_per_ip: 16
  download_delay: 0.1
  download_timeout: 10
  dns_timeout: 5
  retry_enabled: true
  retry_times: 2
  robotstxt_obey: false
  user_agent: "UConn-Discovery-Crawler/1.0 (development)"
  log_level: "INFO"
  request_fingerprinter_implementation: "2.7"

# Stage-specific settings
stages:
  discovery:
    spider_name: "discovery"
    allowed_domains:
      - "uconn.edu"
    max_depth: 3
    output_file: "data/processed/stage01/discovery_output.jsonl"
    seed_file: "data/raw/uconn_urls.csv"
    use_persistent_dedup: true
    dedup_cache_path: "data/cache/url_cache.db"
    # Headless browser for JavaScript-rendered content
    headless_browser:
      enabled: true
      engine: "playwright"  # Options: playwright, selenium
      browser_type: "chromium"  # Options: chromium, firefox, webkit
      headless: true
      timeout: 30000  # milliseconds
      wait_for_selector: null  # Optional CSS selector to wait for
      screenshot_on_error: false
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
      viewport:
        width: 1920
        height: 1080
    heuristics:
      dynamic_script_hints:
        - "fetch("
        - "xmlhttprequest"
        - "axios"
        - "$.get"
        - "$.post"
        - ".ajax"
        - "loadmore"
        - "nexturl"
        - "next_url"
        - "load_more"
        - "apiurl"
        - "api_url"
        - "dispatch("
      json_url_key_hints:
        - "url"
        - "href"
        - "link"
        - "endpoint"
        - "action"
        - "download"
      data_attribute_candidates:
        - "data-url"
        - "data-src"
        - "data-endpoint"
        - "data-load"
        - "data-load-url"
        - "data-href"
        - "data-link"
        - "data-api"
        - "data-request-url"
        - "data-action"
        - "data-next"
        - "data-feed"

  validation:
    max_workers: 16
    timeout: 15
    output_file: "data/processed/stage02/validated_urls.jsonl"
    # Retry strategy configuration
    retry:
      max_attempts: 3  # Maximum retry attempts for most errors
      base_delay: 1.0  # Base delay in seconds for exponential backoff
      max_delay: 60.0  # Maximum delay in seconds
      exponential_base: 2.0  # Exponential backoff base (delay = base * exponential_base^attempt)
      jitter_factor: 0.1  # Jitter ±10% to prevent thundering herd
      transient_max_attempts: 5  # More retries for transient network errors
      rate_limit_max_attempts: 3  # Retries for 429/503 rate limit errors
      rate_limit_base_delay: 5.0  # Longer initial delay for rate limits
    # Circuit breaker configuration (per-domain)
    circuit_breaker:
      failure_threshold: 5  # Open circuit after N consecutive failures
      success_threshold: 2  # Close circuit after N successes in half-open state
      timeout: 60.0  # Seconds before attempting to close circuit

  enrichment:
    spider_name: "enrichment"
    allowed_domains:
      - "uconn.edu"
    nlp_enabled: true
    max_text_length: 20000
    top_keywords: 15
    batch_size: 1000
    output_file: "data/processed/stage03/enrichment_output.jsonl"
    storage:
      backend: jsonl
      rotation: {}
      compression:
        codec: none

    # Headless browser for JavaScript-rendered content
    headless_browser:
      enabled: true
      engine: "playwright"
      browser_type: "chromium"
      headless: true
      timeout: 30000
      wait_for_selector: null
      screenshot_on_error: false
    # Content type handling
    content_types:
      enabled_types:
        - "text/html"
        - "application/pdf"
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "video/mp4"
        - "video/webm"
        - "audio/mpeg"
        - "audio/wav"
      pdf:
        extract_text: true
        extract_metadata: true
        max_pages: 100
      media:
        extract_metadata: true
        download_thumbnails: false
        thumbnail_dir: "data/processed/media/thumbnails"

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  catalog_dir: "data/catalog"
  cache_dir: "data/cache"
  exports_dir: "data/exports"
  logs_dir: "data/logs"
  temp_dir: "data/temp"

# Queue backpressure settings
queue:
  max_queue_size: 10000
  batch_size: 1000
  backpressure_warning_threshold: 0.8  # Warn when queue is 80% full
  backpressure_critical_threshold: 0.95  # Critical when 95% full

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/pipeline.log"
  max_bytes: 10485760
  backup_count: 3
  structured: false  # Set to true for JSON structured logging

# NLP settings
nlp:
  model: "en_core_web_sm"
  max_text_length: 20000
  top_keywords: 15

# Content filtering
content:
  predefined_tags:
    - "admissions"
    - "about"
    - "research"
    - "students"
    - "faculty"
    - "staff"
    - "alumni"
    - "athletics"
    - "covid"
    - "graduate"
    - "undergraduate"
    - "catalog"
    - "courses"
    - "registrar"
    - "financial-aid"
    - "scholarships"
    - "library"
    - "majors"
    - "minors"
    - "housing"
    - "dining"
    - "parking"
    - "sustainability"
    - "environment"
    - "international"
    - "global"
    - "diversity"
    - "inclusion"
    - "policy"
    - "news"
    - "events"
    - "calendar"
    - "maps"
    - "careers"
    - "jobs"
    - "wellness"
    - "health"
    - "engineering"
    - "law"
    - "medicine"
    - "business"
    - "nursing"
    - "education"
    - "pharmacy"
    - "fine-arts"
    - "humanities"
    - "psychology"
    - "biology"
    - "chemistry"
    - "physics"
    - "geosciences"
    - "data"
    - "ai"
    - "robotics"
    - "institute"
    - "center"
# Alerting configuration
alerts:
  enabled: false  # Set to true to enable alerting
  severity_threshold: "error"  # Minimum severity: info, warning, error, critical
  alert_file: "data/logs/alerts.jsonl"
  channels: []
    # Example email channel:
    # - type: email
    #   smtp_host: smtp.gmail.com
    #   smtp_port: 587
    #   smtp_user: your-email@gmail.com
    #   smtp_password: your-app-password
    #   from_addr: your-email@gmail.com
    #   to_addrs:
    #     - recipient@example.com
    #   use_tls: true
    #
    # Example webhook channel (Slack):
    # - type: webhook
    #   url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
    #   format: slack
    #
    # Example file channel:
    # - type: file
    #   path: data/logs/alerts.log
    #   format: text