environment: production

# Scrapy settings
scrapy:
  concurrent_requests: 128
  concurrent_requests_per_domain: 64
  concurrent_requests_per_ip: 64
  download_delay: 0.05
  download_timeout: 15
  dns_timeout: 3
  retry_enabled: true
  retry_times: 3
  robotstxt_obey: false
  user_agent: "UConn-Discovery-Crawler/1.0"
  log_level: "INFO"
  request_fingerprinter_implementation: "2.7"

# Stage-specific settings
stages:
  discovery:
    spider_name: "discovery"
    allowed_domains:
      - "uconn.edu"
    max_depth: 5
    output_file: "data/processed/stage01/new_urls.jsonl"
    seed_file: "data/raw/uconn_urls.csv"
    use_persistent_dedup: true
    dedup_cache_path: "data/cache/url_cache.db"
    headless_browser:
      enabled: true
      engine: "playwright"
      browser_type: "chromium"
      headless: true
      timeout: 30000
      wait_for_selector: null
      screenshot_on_error: false
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
      viewport:
        width: 1920
        height: 1080
    heuristics:
      dynamic_script_hints:
        - "fetch("
        - "xmlhttprequest"
        - "axios"
        - "$.get"
        - "$.post"
        - ".ajax"
        - "loadmore"
        - "nexturl"
        - "next_url"
        - "load_more"
        - "apiurl"
        - "api_url"
        - "dispatch("
      json_url_key_hints:
        - "url"
        - "href"
        - "link"
        - "endpoint"
        - "action"
        - "download"
      data_attribute_candidates:
        - "data-url"
        - "data-src"
        - "data-endpoint"
        - "data-load"
        - "data-load-url"
        - "data-href"
        - "data-link"
        - "data-api"
        - "data-request-url"
        - "data-action"
        - "data-next"
        - "data-feed"

  validation:
    max_workers: 32
    timeout: 10
    output_file: "data/processed/stage02/validated_urls.jsonl"

  enrichment:
    spider_name: "enrichment"
    allowed_domains:
      - "uconn.edu"
    nlp_enabled: true
    max_text_length: 20000
    top_keywords: 15
    batch_size: 2000
    output_file: "data/processed/stage03/enrichment_output.jsonl"
    storage:
      backend: jsonl
      rotation: {}
      compression:
        codec: none

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  catalog_dir: "data/catalog"
  cache_dir: "data/cache"
  exports_dir: "data/exports"
  logs_dir: "data/logs"
  temp_dir: "data/temp"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/pipeline.log"
  max_bytes: 52428800
  backup_count: 5

# NLP settings
nlp:
  model: "en_core_web_sm"
  max_text_length: 20000
  top_keywords: 15

# Content filtering
content:
  predefined_tags:
    - "admissions"
    - "about"
    - "research"
    - "students"
    - "faculty"
    - "staff"
    - "alumni"
    - "athletics"
    - "covid"
    - "graduate"
    - "undergraduate"
    - "catalog"
    - "courses"
    - "registrar"
    - "financial-aid"
    - "scholarships"
    - "library"
    - "majors"
    - "minors"
    - "housing"
    - "dining"
    - "parking"
    - "sustainability"
    - "environment"
    - "international"
    - "global"
    - "diversity"
    - "inclusion"
    - "policy"
    - "news"
    - "events"
    - "calendar"
    - "maps"
    - "careers"
    - "jobs"
    - "wellness"
    - "health"
    - "engineering"
    - "law"
    - "medicine"
    - "business"
    - "nursing"
    - "education"
    - "pharmacy"
    - "fine-arts"
    - "humanities"
    - "psychology"
    - "biology"
    - "chemistry"
    - "physics"
    - "geosciences"
    - "data"
    - "ai"
    - "robotics"
    - "institute"
    - "center"ter"