name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          } else {
            pip install pytest pytest-asyncio pytest-cov pytest-xdist ruff
          }

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests (with coverage if src path exists)
        shell: pwsh
        run: |
          $covTarget = "Scraping_project/src"
          if (Test-Path $covTarget) {
            pytest -q --maxfail=1 -n auto --cov=$covTarget --cov-report=xml
          } else {
            pytest -q --maxfail=1 -n auto
          }

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore
